<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260722160827 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create push_subscriptions table for browser push notifications';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE push_subscriptions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, endpoint TEXT NOT NULL, p256dh VARCHAR(100) NOT NULL, auth_token VARCHAR(50) NOT NULL, last_changes TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3FEC449DC4420F7B ON push_subscriptions (endpoint)');
        $this->addSql('CREATE INDEX IDX_3FEC449DA76ED395 ON push_subscriptions (user_id)');
        $this->addSql('CREATE INDEX IDX_3FEC449D166D1F9C ON push_subscriptions (project_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_project ON push_subscriptions (user_id, project_id)');
        $this->addSql('ALTER TABLE push_subscriptions ADD CONSTRAINT FK_3FEC449DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE push_subscriptions ADD CONSTRAINT FK_3FEC449D166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE push_subscriptions DROP CONSTRAINT FK_3FEC449DA76ED395');
        $this->addSql('ALTER TABLE push_subscriptions DROP CONSTRAINT FK_3FEC449D166D1F9C');
        $this->addSql('DROP TABLE push_subscriptions');
    }
}
