<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Page extends \App\Entity\Page implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'deletedAt' => [parent::class, 'deletedAt', null, 16],
        "\0".parent::class."\0".'editedAt' => [parent::class, 'editedAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'project' => [parent::class, 'project', null, 16],
        "\0".parent::class."\0".'tasks' => [parent::class, 'tasks', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        "\0".parent::class."\0".'version' => [parent::class, 'version', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'deletedAt' => [parent::class, 'deletedAt', null, 16],
        'editedAt' => [parent::class, 'editedAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'project' => [parent::class, 'project', null, 16],
        'tasks' => [parent::class, 'tasks', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'user' => [parent::class, 'user', null, 16],
        'version' => [parent::class, 'version', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
