<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Task extends \App\Entity\Task implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'assignee' => [parent::class, 'assignee', null, 16],
        "\0".parent::class."\0".'children' => [parent::class, 'children', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'createdBy' => [parent::class, 'createdBy', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isPriority' => [parent::class, 'isPriority', null, 16],
        "\0".parent::class."\0".'order' => [parent::class, 'order', null, 16],
        "\0".parent::class."\0".'page' => [parent::class, 'page', null, 16],
        "\0".parent::class."\0".'parent' => [parent::class, 'parent', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'text' => [parent::class, 'text', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'updatedBy' => [parent::class, 'updatedBy', null, 16],
        'assignee' => [parent::class, 'assignee', null, 16],
        'children' => [parent::class, 'children', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'createdBy' => [parent::class, 'createdBy', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isPriority' => [parent::class, 'isPriority', null, 16],
        'order' => [parent::class, 'order', null, 16],
        'page' => [parent::class, 'page', null, 16],
        'parent' => [parent::class, 'parent', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'text' => [parent::class, 'text', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'updatedBy' => [parent::class, 'updatedBy', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
