<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOIx4bb4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOIx4bb4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOIx4bb4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOIx4bb4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOIx4bb4\App_KernelDevDebugContainer([
    'container.build_hash' => 'OIx4bb4',
    'container.build_id' => 'c0e0288d',
    'container.build_time' => 1783615460,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOIx4bb4');
